### ISSUE TITLE
redis perfomance

### ISSUE THREAD

**Issue by R-omk** [kristinn/go-bloom#1]
What do you mean about  bad Redis performance?
I wanted to try redis for bloom filter, what can be pitfalls?

**Comment by kristinn** [comment]
The code is 2 years old and I never finished it. I might take it up again. 😄 

If I recall correctly, at the time I wrote the code, the tcp handshake overhead when talking with redis was causing too much latency, handshake + having to wait for reply for every packet. I should be able to solve it by using the raw redis protocol.

Maybe this has been changed in the last 2 years though. I will take a look and see if I can fix it and finish this project.

**Comment by kristinn** [comment]
The operation in question is the bulk insert of data. It would be best to be able to throw the data in there and not think about it - since there are anyways always false positives.

At least, the bottom line is that the insert of data into redis is way too slow (if I recall correctly).

**Comment by R-omk** [comment]
Maybe  worth using pipeline instead of MULTI. This will reduce rtt with redis. And why redis connection pool?  Redis is single thread  application,  it will not be able to process requests faster than it can.

**Comment by kristinn** [comment]
Yeah, I don't remember the details. Haven't given this a thought for 2 years now.

**Comment by kristinn** [comment]
I made few changes https://github.com/kristinn/go-bloom/commit/d6d22a12068459d28f4f2545436ff6c3da542bab

There were errors in the benchmarks which caused them to show far worse outcome than expected.

Now it's only using pipelining. Changing from multi to pipelining didn't affect the performance much though.

The redis pool is just a connection pooling. I doubt that affects the performance at all, rather the other way around (I haven't done any benchmarking on it though).

**Comment by kristinn** [comment]
I'm pretty satisfied with the Redis benchmarks now. There were also errors in the benchmarking code which caused it to show couple hundred percent higher numbers than was expected. 😛 

I encourage you to try it out for yourself.

**Comment by R-omk** [comment]
I use your code for a week in a highly loaded system. All works fine!  Many thanks for you time!

**Comment by kristinn** [comment]
That is great to hear! You are very welcome!
